### ISSUE TITLE
Support to specify the hostname of the route to be created from a service

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#14]
Support to specify the hostname of the route to be created from a service instead of using the cluster's internal service name

```
spec:
  link:
    name: Route hostname to be injected as EnvVar using fruit-backend's Route
    targetcomponentname: fruit-client
    kind: Route
    ref: fruit-backend
```
