### ISSUE TITLE
Implement capability contracts for components

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#146]
## Description of the problem

The biggest friction we have at the moment with halkyon is that we still have to figure out the wiring manually.

i.e. if a client service needs a backend endpoint, you need to know that the client expects to be injected an endpoint URL in an env variable and know the env name. you will also need to know the URL of the backend service to be able to inject it in the client service as an env link type

The issues I see with this are multiple: 

1. we offer 2 types of links, why should one select one over the other? how do you make that choice? Unclear
2. you need to know what the client app is requiring and in what form (e.g. environment variable named FOO) but you don't currently have access to that information at the halkyon level
3. you need to know the url of the backend service even though that's highly dependent on how that service is deployed and then enter it manually

## Proposition

Based on that, I started thinking that components should have contracts
this would also tie up with the capability concept in a more natural way

a component could define a set of required capabilities and a set of provided capabilities: 
- required capabilities would indicate the type of capability and how the component expect them
- provided capabilities would indicate the kind of services the component is capable of providing
a component couldn't move to the running state without all its required capabilities being satisfied
we could also have optional capabilities but let's not worry about that now

So the client-server interaction would be solved the following way

client specifies: requires a REST capability (i.e. I need an endpoint to connect to) and expect the URL to be provided as ENDPOINT variable
this would be part of the component definition (syntax/semantics TBD)
this could maybe be helped with by dekorate (not sure yet)
this way, the designer of the component / app, lets the rest of the world know what the component needs to be running

On the other side, we have the backend component
there, dekorate can help quite a bit
Based on the analysis we already do on the app, we know that the app exposes endpoints, we could know on what URLs (relative to the app's context) and on what port
So we could automatically generate provided capabilities for the backend component

**Now, how do things tie together?**
well, when you create your app, you will want to link the client with the backend
so hal could look at provided capabilities that match the from component required capabilities and offer to create a "connection" between them
the link could then be automatically created without the user having to know about which env variable to use or how the backend URL is composed
the only thing the user will need to decide is which of the exposed URLs to use
but the rest could (and should) be quite transparent

So is this just some crazy, sleep deprived idea or could this actually make sense?

Example: for the database use case, we could generate a datasource based on the provided contract of the target capability that would be a little more complex to handle
but I could see it working though it might require smarter runtime images (i.e. we might need to be able to run code on the runtime images to do the datasource creation manipulation in a runtime-agnostic way from halkyon)

So a client component could look like:

```
spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    capabilities:
      required:
        - type: "rest"
          parameters:
            - name: "expectedVar"
              value: "ENDPOINT"
      provided:
        - type: "url"
          parameters:
            - name: "context"
              value: "/foo"
            - name: "port"
              value: 8080
```

and the backend component:
```
spec:
    deploymentMode: "dev"
    runtime: "spring-boot"
    version: "2.1.6.RELEASE"
    capabilities:
      required:
        - type: "database"
          parameters:
            - name: "datasourceName"
              value: "myDB"
      provided:
        - type: "rest"
          parameters:
            - name: "context"
              value: "/api"
            - name: "port"
              value: 8080
            - name: "endpoints"
              value:
                - "/foo"
                - "/bar"
```
