### ISSUE TITLE
CRD should allow for setting of Limits / Requests and Health Check timeouts

### ISSUE THREAD

**Issue by jbride** [halkyonio/operator#164]
Production OpenShift environments tend to have a LimitRange on all namespaces set by the cluster admin.  The default limit and requests can intentionally be set very low.

ie:  

```
apiVersion: v1
kind: LimitRange
metadata:
  name: halkyon-fruit-core-resource-limits
  namespace: halkyon-fruit
  uid: a4129dd9-e48e-11e9-887c-2cabcdef0010
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
```

The Component CRD provided by Halkyon doesn't appear to allow an app developer with the ability to set limits and requests.  Subsequently, corresponding linux containers are at the mercy of the default limit and requests set by a cluster admin.  These intentionally low limits and requests could very likely not even be sufficient to execute a maven build.  Subsequently,   _hal component push ...... _  will not work.

Semi-related is the need to also allow an app developer to define health check timeouts on their Components.

thanks!
