### ISSUE TITLE
Integrate with Knative

### ISSUE THREAD

**Issue by gunnarmorling** [halkyonio/operator#180]
It should be possible to deploy Halkyon components as Knative services, so that they e.g. benefit from auto-scaling // CC @matzew, @rolandhuss.

**Comment by cmoulliard** [comment]
> as Knative services

Yes. What I propose is then to have :
- A new field to the Operator Api in order to tell to the operator that we would like to install wither a `Knative service resource` or  a `K8s Service resource`
- Register the Knative Service API to let the Operator to generate the KNative Service

Idea
```
#
apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: http-rest-sb
spec:
  serviceType: knative // or kubernetes
```
