### ISSUE TITLE
Service still exposed as ClusterIP

### ISSUE THREAD

**Issue by jponge** [halkyonio/operator#187]
Given the following resource:

```yaml
apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: rain-service
spec:
  runtime: vert.x
  version: 3.8.3
  deploymentMode: dev
  port: 8080
  exposeService: true
```

I get a service that is still exposed as a `ClusterIP`:

```
kgs
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes     ClusterIP   10.96.0.1       <none>        443/TCP    8m49s
rain-service   ClusterIP   10.96.214.123   <none>        8080/TCP   5m1s
```

Tested on Minikube. I could not reproduce this under MicroK8S since for some reason the service does not start (using manual `kubctl cp` / `kubectl exec` commands).
