### ISSUE TITLE
Change docker version when release is tagged

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#25]
The version of the docker image of the operator yaml resource must be changed when we tag/release the project using circleci

```
spec:
  replicas: 1
  selector:
    matchLabels:
      name: component-operator
  template:
    metadata:
      labels:
        name: component-operator
    spec:
      serviceAccountName: component-operator
      containers:
        - name: component-operator
          image: quay.io/snowdrop/component-operator:master --> 0.0.1, .....
```
see : https://github.com/snowdrop/component-operator/blob/master/deploy/operator.yaml#L18

**REMARK**. We should perhaps use `master` as version number or a dummy version to avoid show such info within the log of the operator for a non released 

```
2018/12/17 18:02:16 Go Version: go1.11.3
--
  | 2018/12/17 18:02:16 Go OS/Arch: linux/amd64
  | 2018/12/17 18:02:16 operator-sdk Version: v0.1.1
  | 2018/12/17 18:02:16 component-operator version: 0.0.1
  | 2018/12/17 18:02:16 Registering Components.
  | 2018/12/17 18:02:16 Starting the Cmd.


```
