### ISSUE TITLE
Convention to respect to create the labels and component name

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#49]
### Enhancement

I propose that we adopt the following convention to create :  

1) Component metadata name

- For a Maven project, we use as Component metadata name the artifactId
- For a Gradle project we use the Gradle description where we convert the title in lower cases and replace the space with "-" [1]

2) Labels

- For a Maven/Gradle project, we will include the following labels
```
    labels:
      app: <artifactID> OR <gradle_description_lowercase_with_hyphen>
      version: <project_version>
      group: <???>
```

Question: What should we do for the group field ? My idea is to specify there the project or application to which the component or module belong to ? Where can we get such info ?

WDYT: @iocanel @geoand @aureamunoz @metacosm 

[1] https://github.com/spring-projects/spring-framework/blob/master/spring-beans/spring-beans.gradle#L1
