### ISSUE TITLE
Improve capability support

### ISSUE THREAD

**Issue by metacosm** [halkyonio/operator#59]
Capabilities are currently tied to the concept of Service Catalog. We need to decouple capabilities from Services so that they could cover more use cases such as creating monitoring resources.
Moreover, linking to a capability currently requires the user to know how they work so that they can use the proper linking strategy. This could be improved by the capability providing this information so that the proper strategy could be picked transparently when a link is created.

**Comment by cmoulliard** [comment]
> Capabilities are currently tied to the concept of Service Catalog. We need to decouple capabilities from Services

I completely agree as the idea of the capability should in a later release of the APi and Component Operator to populate `Prometheus`, `Jaeger`, ... CRDs

**Comment by cmoulliard** [comment]
> This could be improved by the capability providing this information so that the proper strategy could be picked transparently when a link is created.

Do you have an example about what you suggest ?

**Comment by cmoulliard** [comment]
Proposition for the new `Capability spec` definition

Existing mapped with ServiceInstance/ServiceBinding & Secret
```
apiVersion: devexp.runtime.redhat.com/v1alpha2
kind: Capability
metadata:
  name: postgresql-db
spec:
  name: postgresql-db
  class: dh-postgresql-apb
  plan: dev
  secretName: postgresql-db
  parameters:
    - name: postgresql_user
      value: luke"
    - name: postgresql_password
      value: secret
      ...
```

New
```
apiVersion: devexp.runtime.redhat.com/v1alpha2
kind: Capability
metadata:
  name: <capability-name>
spec:
  category: <database>, <logging>,<metrics>
  kind: posgres (if category is database)
  version: <version of the DB or prometheus or ...> to be installed
  secretName: postgresql-db
  parameters:
    - name: DB_USER // WILL BE USED TO CREATE THE DB SECRET
       value: "admin"
    - name: DB_PASSWORD  // WILL BE USED TO CREATE THE DB SECRET
       value: "admin"
    - name: DB_NAME
       value: "my-db"
    - name: DB_INIT_SCRIPT
       value: ConfigMap mounted as volume //WDYT ?
```

WDYT @aureamunoz, @metacosm, @iocanel ?
