### ISSUE TITLE
Service selector is not correct

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#70]
### Service selector

The Service selector defined for the Service created when deployment mode = build is not correct as the pod is not selected

Component
```
#
# TODO: TO be documented that we must configure such security rules on openshift
# oc adm policy add-scc-to-user privileged -z build-bot
# oc adm policy add-role-to-user edit -z build-bot
#
#
apiVersion: devexp.runtime.redhat.com/v1alpha2
kind: Component
metadata:
  name: fruit-backend-sb
  labels:
    app: fruit-backend-sb
spec:
  deploymentMode: build
  buildConfig:
    url: https://github.com/snowdrop/component-operator-demo.git
    ref: master
    moduleDirName: fruit-backend-sb
  runtime: spring-boot
  version: 2.1.3
  envs:
  - name: SPRING_PROFILES_ACTIVE
    value: postgresql-kubedb
  - name: DB_HOST
    value: my-postgres.demo
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: my-database
  - name: DB_USER
    value: admin
  - name: DB_PASSWORD
    value: admin
```

Labels of the build pod created using the component CRD are 
```
  labels:
    app: fruit-backend-sb
    component_cr: fruit-backend-sb
    deployment: fruit-backend-sb
```

but the service labels defined for the selector are
```
  selector:
    app: fruit-backend-sb-build
    component_cr: fruit-backend-sb
    deployment: fruit-backend-sb
```

### Service resource changed

For a reason that I don't know, if we change manually the k8s service resource, then later it is updated and modified

So, after a few minutes the label has been changed to

```
  selector:
    app: fruit-backend-sb-build
    component_cr: fruit-backend-sb
    deployment: fruit-backend-sb
```

see: `app: fruit-backend-sb-build`

**Comment by cmoulliard** [comment]
With the latest code merged = generic reconciler, there is still an issue which is related to how labels are created

So, the service is looking, using its selector, to a pod having these labels
```
  selector:
    app: fruit-client-sb-build
    component_cr: fruit-client-sb-build
    deployment: fruit-client-sb-build
```
but the Deployment created for the `fruit-client-sb` component contains such labels
```
  labels:
    app: fruit-client-sb
    component_cr: fruit-client-sb
    deployment: fruit-client-sb
```
