### ISSUE TITLE
Bind capability parameters to the component

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/operator#75]
## Use case - Bind capability parameters to the component

The controller of the OpenShift Ansible Broker binds the parameters of a service such as a database to a Secret which is next used to inject as `EnvFrom` within the pod the `env vars`.
I suggest to adopt also the same approach with our Capability operator and to do the following tasks

- Create a secret using a default secret name <DB_CONFIG_NAME>.  
- Add to the secret, the following properties where some could be created with default values:
  - name: DB_CONFIG_NAME
     value: <DB_CONFIG_NAME>. Default is the name of the capability suffixed with `-config`. Example `postgres-db --> postgres-db-config`
  - name: DB_HOST
    value: <DB_NAME>. Default is the name of the capability. Example `postgres-db`
  - name: DB_PORT
    value: <DB_PORT>. Default is the port of the database as defined for postgres, mysql, ...
  - name: DB_NAME
    value: <DATABASE_NAME>. Default is `sampledb`
  - name: DB_USER
    value: <DB_USER>. Default is `admin`
  - name: DB_PASSWORD
    value: <DB_PASSWORD. Default is `admin`
- Update the Deployment of the created Deployment to inject the EnvVars using the properties of the secret

Remark : 

Such parameters should be then defined within the Datasource file that ap4k/kreate could populate
```
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
```

This binding mechanism avoids the need to specify additional `ENV VARS` to the Component CRD. If the user accepts the default value, then the DB_CONFIG_NAME will be used to bind the data, otherwise it could override it using a parameter or env var.

```
apiVersion: devexp.runtime.redhat.com/v1alpha2
kind: Component
metadata:
  name: fruit-backend-sb
  labels:
    app: fruit-backend-sb
spec:
  deploymentMode: build
  buildConfig:
    url: https://github.com/snowdrop/component-operator-demo.git
    ref: master
    moduleDirName: fruit-backend-sb
  runtime: spring-boot
  version: 2.1.3
  envs:
  - name: SPRING_PROFILES_ACTIVE
    value: postgresql-kubedb
  - name: DB_CONFIG_NAME
    value: postgres-db-config
```

WDYT : @aureamunoz, @metacosm, @iocanel, @gytis, @geoand, @nainaz @tqvarnst
